ls:
  .md: SCREAMING_SNAKE_CASE

  '{apps,packages}/*/src':
    .dir: kebab-case
    .js: kebab-case
    .*.js: kebab-case
    .jsx: kebab-case
    .*.jsx: kebab-case
    .ts: kebab-case
    .*.ts: kebab-case
    .tsx: kebab-case
    .*.tsx: kebab-case
    .json: kebab-case
    .css: kebab-case
    .scss: regex:_?[a-z]+(?:-[a-z]+)* #kebab-case + optional starting underscore
    .*.scss: kebab-case

ignore:
  - .git
  - node_modules
  - '**/@types'
