packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@compodoc/compodoc': false
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  msw: false
