/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ProductsIndexRouteImport } from './routes/products.index';
import { Route as ProductsProductSlugRouteImport } from './routes/products.$productSlug';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/products/$productSlug': typeof ProductsProductSlugRoute;
  '/products': typeof ProductsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/products/$productSlug': typeof ProductsProductSlugRoute;
  '/products': typeof ProductsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/products/$productSlug': typeof ProductsProductSlugRoute;
  '/products/': typeof ProductsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/products/$productSlug' | '/products';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/products/$productSlug' | '/products';
  id: '__root__' | '/' | '/products/$productSlug' | '/products/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute;
  ProductsIndexRoute: typeof ProductsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products/': {
      id: '/products/';
      path: '/products';
      fullPath: '/products';
      preLoaderRoute: typeof ProductsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products/$productSlug': {
      id: '/products/$productSlug';
      path: '/products/$productSlug';
      fullPath: '/products/$productSlug';
      preLoaderRoute: typeof ProductsProductSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
